version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: DockerfileDev
    command: >
      sh -c "node db/init.js && npm start"
    restart: unless-stopped
    environment:
      - BASE_URL=http://localhost:3000
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey
    ports:
      - 1337:1337
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_PASSWORD=planka
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  db-data: